# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\大三\数据库\实验\pyqt5登陆界面制作\Copying_1006\Lib\itemwidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(480, 575)
        Form.setMinimumSize(QtCore.QSize(250, 360))
        Form.setStyleSheet("frame{border:10px solid rgb(255,255,255)}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setStyleSheet("QFrame{\n"
"    background-color: rgb(245, 249, 254);\n"
"border:0px solid red;\n"
"    color: rgb(255, 254, 255);\n"
"border-radius:30px\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setStyleSheet("QFrame{\n"
"    background-color: rgb(245, 249, 254);\n"
"border:0px solid red;\n"
"    color: rgb(170, 255, 255);\n"
"border-radius:10px\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setStyleSheet("QFrame{\n"
"    background-color: rgb(255, 255, 255);\n"
"border:0px solid red;\n"
"    color: rgb(255, 254, 255);\n"
"border-radius:10px\n"
"}")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.label_id = QtWidgets.QLabel(self.frame_2)
        self.label_id.setStyleSheet("QFrame{\n"
"    background-color: rgb(255, 255, 255);\n"
"border:0px solid red;\n"
"    color: rgb(255, 254, 255);\n"
"border-radius:10px\n"
"}")
        self.label_id.setText("")
        self.label_id.setObjectName("label_id")
        self.horizontalLayout_6.addWidget(self.label_id)
        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(1, 3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setStyleSheet("QFrame{\n"
"    background-color: rgb(255, 255, 255);\n"
"border:0px solid red;\n"
"    color: rgb(255, 254, 255);\n"
"border-radius:10px\n"
"}")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.label_name = QtWidgets.QLabel(self.frame_2)
        self.label_name.setStyleSheet("QFrame{\n"
"    background-color: rgb(255, 255, 255);\n"
"border:0px solid red;\n"
"    color: rgb(255, 254, 255);\n"
"border-radius:10px\n"
"}")
        self.label_name.setText("")
        self.label_name.setObjectName("label_name")
        self.horizontalLayout_5.addWidget(self.label_name)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setStyleSheet("QFrame{\n"
"    background-color: rgb(255, 255, 255);\n"
"border:0px solid red;\n"
"    color: rgb(255, 254, 255);\n"
"border-radius:10px\n"
"}")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.label_id_2 = QtWidgets.QLabel(self.frame_2)
        self.label_id_2.setStyleSheet("QFrame{\n"
"    background-color: rgb(255, 255, 255);\n"
"border:0px solid red;\n"
"    color: rgb(255, 254, 255);\n"
"border-radius:10px\n"
"}")
        self.label_id_2.setText("")
        self.label_id_2.setObjectName("label_id_2")
        self.horizontalLayout_7.addWidget(self.label_id_2)
        self.horizontalLayout_7.setStretch(0, 1)
        self.horizontalLayout_7.setStretch(1, 3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setStyleSheet("QFrame{\n"
"    background-color: rgb(255, 255, 255);\n"
"border:0px solid red;\n"
"    color: rgb(255, 254, 255);\n"
"border-radius:10px\n"
"}")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.label_breed = QtWidgets.QLabel(self.frame_2)
        self.label_breed.setStyleSheet("QFrame{\n"
"    background-color: rgb(255, 255, 255);\n"
"border:0px solid red;\n"
"    color: rgb(255, 254, 255);\n"
"border-radius:10px\n"
"}")
        self.label_breed.setText("")
        self.label_breed.setObjectName("label_breed")
        self.horizontalLayout_4.addWidget(self.label_breed)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setStyleSheet("QFrame{\n"
"    background-color: rgb(255, 255, 255);\n"
"border:0px solid red;\n"
"    color: rgb(255, 254, 255);\n"
"border-radius:10px\n"
"}")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.label_age = QtWidgets.QLabel(self.frame_2)
        self.label_age.setStyleSheet("QFrame{\n"
"    background-color: rgb(255, 255, 255);\n"
"border:0px solid red;\n"
"    color: rgb(255, 254, 255);\n"
"border-radius:10px\n"
"}")
        self.label_age.setText("")
        self.label_age.setObjectName("label_age")
        self.horizontalLayout_3.addWidget(self.label_age)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setStyleSheet("QFrame{\n"
"    background-color: rgb(255, 255, 255);\n"
"border:0px solid red;\n"
"    color: rgb(255, 254, 255);\n"
"border-radius:10px\n"
"}")
        self.label_5.setTextFormat(QtCore.Qt.AutoText)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.label_nature = QtWidgets.QLabel(self.frame_2)
        self.label_nature.setStyleSheet("QFrame{\n"
"    background-color: rgb(255, 255, 255);\n"
"border:0px solid red;\n"
"    color: rgb(255, 254, 255);\n"
"border-radius:10px\n"
"}")
        self.label_nature.setText("")
        self.label_nature.setObjectName("label_nature")
        self.horizontalLayout_2.addWidget(self.label_nature)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(171, 147, 213, 255), stop:1 rgba(255, 255, 255, 255));")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.setStretch(2, 1)
        self.verticalLayout_2.setStretch(3, 1)
        self.verticalLayout_2.setStretch(4, 1)
        self.verticalLayout_2.setStretch(5, 3)
        self.verticalLayout_2.setStretch(6, 2)
        self.verticalLayout.addWidget(self.frame_2)
        self.verticalLayout.setStretch(0, 1)
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_6.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#222222;\">编号：</span></p></body></html>"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#222222;\">名字：</span></p></body></html>"))
        self.label_7.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#222222;\">公母：</span></p></body></html>"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#222222;\">品种：</span></p></body></html>"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#222222;\">年龄：</span></p></body></html>"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#222222;\">性格：</span></p></body></html>"))
        self.pushButton.setText(_translate("Form", "修改&删除"))
