# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\大三\数据库\实验\Copying_1006\main1006.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from Lib.flowlayout import FlowLayout
from Lib import pet_item

from PyQt5.QtGui import QColor, QPixmap, QIcon, QPalette
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication  ,QWidget  , QGridLayout
try:
    from PyQt5.QtCore import QRectF, Qt, QPropertyAnimation, pyqtProperty, \
        QPoint, QParallelAnimationGroup, QEasingCurve
    from PyQt5.QtGui import QPainter, QPainterPath, QColor, QPen
    from PyQt5.QtWidgets import QLabel, QWidget, QVBoxLayout, QApplication, \
        QLineEdit, QPushButton
except ImportError:
    from PySide2.QtCore import QRectF, Qt, QPropertyAnimation, Property as pyqtProperty, \
        QPoint, QParallelAnimationGroup, QEasingCurve
    from PySide2.QtGui import QPainter, QPainterPath, QColor, QPen
    from PySide2.QtWidgets import QLabel, QWidget, QVBoxLayout, QApplication, \
        QLineEdit, QPushButton


class Ui_StartWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1129, 693)
        self.start_x = None
        self.start_y = None
        self.anim = None
        self.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.setWindowFlags(Qt.FramelessWindowHint)  # 设置窗口标志：隐藏窗口边框
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("QFrame{\n"
"    background-color: qlineargradient(spread:pad, x1:0.438, y1:0.568591, x2:1, y2:1, stop:0 rgba(241, 238, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border:0px solid red;\n"
"border-radius:30px\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setSpacing(12)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_12.setSpacing(36)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_7 = QtWidgets.QFrame(self.frame_3)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.verticalLayout_12.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(self.frame_3)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_12 = QtWidgets.QFrame(self.frame_8)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.widget_6 = QtWidgets.QWidget(self.frame_12)
        self.widget_6.setMinimumSize(QtCore.QSize(64, 64))
        self.widget_6.setMaximumSize(QtCore.QSize(64, 64))
        self.widget_6.setStyleSheet("image: url(:/svg/img/svg/女孩1.png);\n"
"border:3px solid rgb(255, 255, 255);\n"
"background-color: rgb(12, 20, 36);\n"
"border-radius:32px")
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_14.addWidget(self.widget_6)
        self.verticalLayout_11.addWidget(self.frame_12)
        self.label_23 = QtWidgets.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_11.addWidget(self.label_23)
        self.verticalLayout_12.addWidget(self.frame_8)
        self.frame_9 = QtWidgets.QFrame(self.frame_3)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_12.addWidget(self.frame_9)
        self.stackedWidget_5 = QtWidgets.QStackedWidget(self.frame_3)
        self.stackedWidget_5.setStyleSheet("QFrame{\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.stackedWidget_5.setObjectName("stackedWidget_5")
        self.stackedWidget_5Page1 = QtWidgets.QWidget()
        self.stackedWidget_5Page1.setObjectName("stackedWidget_5Page1")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.stackedWidget_5Page1)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.listWidget_2 = QtWidgets.QListWidget(self.stackedWidget_5Page1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.listWidget_2.setFont(font)
        self.listWidget_2.setStyleSheet("QListView {\n"
"\n"
"}\n"
"QListView::item{\n"
"background-color: transparent;\n"
"    color: rgb(184, 184, 184);\n"
"padding:8px;\n"
"padding-left:4px;\n"
"margin-bottom:8px;\n"
"}\n"
"QListView::item:hover {\n"
"border-radius:8px;\n"
"    background-color: rgb(240, 240, 240)\n"
"\n"
"}\n"
"QListView::item:selected {\n"
"    background-color: rgb(239, 239, 239);\n"
"    color: rgb(12, 20, 36);\n"
"border-radius:8px;\n"
"}\n"
"")
        self.listWidget_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidget_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidget_2.setObjectName("listWidget_2")
        item = QtWidgets.QListWidgetItem()
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/svg/img/svg/主页.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon)
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/svg/img/svg/联系人.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon1)
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/svg/img/svg/博士帽.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon2)
        self.listWidget_2.addItem(item)
        self.horizontalLayout_21.addWidget(self.listWidget_2)
        self.stackedWidget_5.addWidget(self.stackedWidget_5Page1)
        self.stackedWidget_5Page2 = QtWidgets.QWidget()
        self.stackedWidget_5Page2.setObjectName("stackedWidget_5Page2")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.stackedWidget_5Page2)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.listWidget_3 = QtWidgets.QListWidget(self.stackedWidget_5Page2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.listWidget_3.setFont(font)
        self.listWidget_3.setStyleSheet("QListView {\n"
"\n"
"}\n"
"QListView::item{\n"
"background-color: transparent;\n"
"    color: rgb(184, 184, 184);\n"
"padding:8px;\n"
"padding-left:4px;\n"
"margin-bottom:8px;\n"
"}\n"
"QListView::item:hover {\n"
"border-radius:8px;\n"
"    background-color: rgb(240, 240, 240)\n"
"\n"
"}\n"
"QListView::item:selected {\n"
"    background-color: rgb(239, 239, 239);\n"
"    color: rgb(12, 20, 36);\n"
"border-radius:8px;\n"
"}\n"
"")
        self.listWidget_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidget_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidget_3.setObjectName("listWidget_3")
        item = QtWidgets.QListWidgetItem()
        item.setIcon(icon)
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setIcon(icon1)
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/svg/img/svg/205设置.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon3)
        self.listWidget_3.addItem(item)
        self.horizontalLayout_22.addWidget(self.listWidget_3)
        self.stackedWidget_5.addWidget(self.stackedWidget_5Page2)
        self.verticalLayout_12.addWidget(self.stackedWidget_5)
        self.frame_10 = QtWidgets.QFrame(self.frame_3)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_16.setContentsMargins(24, 0, -1, 12)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_10)
        self.pushButton_4.setStyleSheet("color: rgb(199, 199, 199);\n"
"border:none;\n"
"text-align:left;\n"
"padding:12px;")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/buttom/img/buttom/退出文件夹_folder-withdrawal.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon4)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_16.addWidget(self.pushButton_4, 0, QtCore.Qt.AlignBottom)
        self.verticalLayout_12.addWidget(self.frame_10)
        self.verticalLayout_12.setStretch(1, 1)
        self.verticalLayout_12.setStretch(4, 1)
        self.horizontalLayout_18.addWidget(self.frame_3)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setStyleSheet("QFrame{\n"
"    background-color: rgb(255, 255, 255);\n"
"border:0px solid red;\n"
"border-radius:30px\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_13.setContentsMargins(24, 24, 24, 24)
        self.verticalLayout_13.setSpacing(24)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_2)
        self.stackedWidget.setStyleSheet("QFrame{\n"
"    background-color: rgb(255, 255, 255);\n"
"border:0px solid red;\n"
"    color: rgb(255, 254, 255);\n"
"border-radius:30px\n"
"}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_0 = QtWidgets.QWidget()
        self.page_0.setObjectName("page_0")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.page_0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_4 = QtWidgets.QFrame(self.page_0)
        self.frame_4.setStyleSheet("QFrame{\n"
"    background-color: rgb(255, 255, 255);\n"
"border:0px solid red;\n"
"    color: rgb(255, 254, 255);\n"
"border-radius:30px\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.frame_4)
        self.scrollArea_2.setStyleSheet("*{\n"
"    background-color: rgb(255, 255, 255);\n"
"border:0px solid red;\n"
"    color: rgb(255, 254, 255);\n"
"border-radius:30px\n"
"}")
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 711, 599))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_4.addWidget(self.scrollArea_2)
        self.horizontalLayout_3.addWidget(self.frame_4)
        self.stackedWidget.addWidget(self.page_0)
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.page_1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_5 = QtWidgets.QFrame(self.page_1)
        self.frame_5.setStyleSheet("QFrame{\n"
"    background-color: rgb(255, 255, 255);\n"
"border:0px solid red;\n"
"    color: rgb(255, 254, 255);\n"
"border-radius:30px\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.widget_3 = QtWidgets.QWidget(self.frame_5)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.widget_4 = QtWidgets.QWidget(self.widget_3)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_22 = QtWidgets.QFrame(self.widget_4)
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.frame_22)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        spacerItem = QtWidgets.QSpacerItem(210, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(self.frame_22)
        self.label_2.setStyleSheet("QFrame{\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0.577, y1:0.522727, x2:1, y2:1, stop:0 rgba(201, 187, 241, 253), stop:1 rgba(255, 255, 255, 255));\n"
"border:0px solid red;\n"
"    color: rgb(255, 254, 255);\n"
"border-radius:10px\n"
"}\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_20.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(210, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem1)
        self.horizontalLayout_20.setStretch(0, 1)
        self.horizontalLayout_20.setStretch(1, 1)
        self.horizontalLayout_20.setStretch(2, 1)
        self.verticalLayout.addWidget(self.frame_22)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.frame_11 = QtWidgets.QFrame(self.widget_4)
        self.frame_11.setStyleSheet("QFrame{\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0.438, y1:0.568591, x2:1, y2:1, stop:0 rgba(241, 238, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border:0px solid red;\n"
"    color: rgb(255, 254, 255);\n"
"border-radius:15px\n"
"}")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label = QtWidgets.QLabel(self.frame_11)
        self.label.setStyleSheet("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_8.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.frame_11)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_8.addWidget(self.lineEdit)
        self.horizontalLayout_27.addWidget(self.frame_11)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem2)
        self.frame_13 = QtWidgets.QFrame(self.widget_4)
        self.frame_13.setStyleSheet("QFrame{\n"
"    background-color: qlineargradient(spread:pad, x1:0.438, y1:0.568591, x2:1, y2:1, stop:0 rgba(241, 238, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border:0px solid red;\n"
"    color: rgb(255, 254, 255);\n"
"border-radius:15px\n"
"}")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_6 = QtWidgets.QLabel(self.frame_13)
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_9.addWidget(self.label_6)
        self.comboBox = QtWidgets.QComboBox(self.frame_13)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_9.addWidget(self.comboBox)
        self.horizontalLayout_27.addWidget(self.frame_13)
        self.horizontalLayout_27.setStretch(0, 3)
        self.horizontalLayout_27.setStretch(2, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.frame_14 = QtWidgets.QFrame(self.widget_4)
        self.frame_14.setStyleSheet("QFrame{\n"
"    background-color: qlineargradient(spread:pad, x1:0.438, y1:0.568591, x2:1, y2:1, stop:0 rgba(241, 238, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border:0px solid red;\n"
"    color: rgb(255, 254, 255);\n"
"border-radius:15px\n"
"}")
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_10 = QtWidgets.QLabel(self.frame_14)
        self.label_10.setStyleSheet("")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame_14)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_10.addWidget(self.lineEdit_5)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem3)
        self.horizontalLayout_29.addWidget(self.frame_14)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem4)
        self.frame_15 = QtWidgets.QFrame(self.widget_4)
        self.frame_15.setStyleSheet("QFrame{\n"
"    background-color: qlineargradient(spread:pad, x1:0.438, y1:0.568591, x2:1, y2:1, stop:0 rgba(241, 238, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border:0px solid red;\n"
"    color: rgb(255, 254, 255);\n"
"border-radius:15px\n"
"}")
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_11 = QtWidgets.QLabel(self.frame_15)
        self.label_11.setStyleSheet("")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_28.addWidget(self.label_11)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.frame_15)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.horizontalLayout_28.addWidget(self.lineEdit_8)
        self.horizontalLayout_29.addWidget(self.frame_15)
        self.horizontalLayout_29.setStretch(0, 1)
        self.horizontalLayout_29.setStretch(2, 3)
        self.verticalLayout.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.frame_18 = QtWidgets.QFrame(self.widget_4)
        self.frame_18.setStyleSheet("QFrame{\n"
"    background-color: qlineargradient(spread:pad, x1:0.438, y1:0.568591, x2:1, y2:1, stop:0 rgba(241, 238, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border:0px solid red;\n"
"    color: rgb(255, 254, 255);\n"
"border-radius:15px\n"
"}")
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_18)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_9 = QtWidgets.QLabel(self.frame_18)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_12.addWidget(self.label_9)
        self.spinBox = QtWidgets.QSpinBox(self.frame_18)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_12.addWidget(self.spinBox)
        self.horizontalLayout_32.addWidget(self.frame_18)
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_32.addItem(spacerItem5)
        self.frame_19 = QtWidgets.QFrame(self.widget_4)
        self.frame_19.setStyleSheet("QFrame{\n"
"    background-color: qlineargradient(spread:pad, x1:0.438, y1:0.568591, x2:1, y2:1, stop:0 rgba(241, 238, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border:0px solid red;\n"
"    color: rgb(255, 254, 255);\n"
"border-radius:15px\n"
"}")
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout(self.frame_19)
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.checkBox = QtWidgets.QCheckBox(self.frame_19)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_33.addWidget(self.checkBox)
        self.horizontalLayout_32.addWidget(self.frame_19)
        self.horizontalLayout_32.setStretch(0, 6)
        self.horizontalLayout_32.setStretch(1, 1)
        self.horizontalLayout_32.setStretch(2, 6)
        self.verticalLayout.addLayout(self.horizontalLayout_32)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.frame_16 = QtWidgets.QFrame(self.widget_4)
        self.frame_16.setStyleSheet("QFrame{\n"
"    background-color:qlineargradient(spread:pad, x1:0.438, y1:0.568591, x2:1, y2:1, stop:0 rgba(241, 238, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border:0px solid red;\n"
"    color: rgb(255, 254, 255);\n"
"border-radius:15px\n"
"}")
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_16)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_12 = QtWidgets.QLabel(self.frame_16)
        self.label_12.setStyleSheet("")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_11.addWidget(self.label_12)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame_16)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_11.addWidget(self.lineEdit_6)
        self.horizontalLayout_30.addWidget(self.frame_16)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_30.addItem(spacerItem6)
        self.frame_17 = QtWidgets.QFrame(self.widget_4)
        self.frame_17.setStyleSheet("QFrame{\n"
"    background-color: qlineargradient(spread:pad, x1:0.438, y1:0.568591, x2:1, y2:1, stop:0 rgba(241, 238, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border:0px solid red;\n"
"    color: rgb(255, 254, 255);\n"
"border-radius:15px\n"
"}")
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout(self.frame_17)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.label_13 = QtWidgets.QLabel(self.frame_17)
        self.label_13.setStyleSheet("")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_31.addWidget(self.label_13)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.frame_17)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.horizontalLayout_31.addWidget(self.lineEdit_9)
        self.horizontalLayout_30.addWidget(self.frame_17)
        self.horizontalLayout_30.setStretch(0, 6)
        self.horizontalLayout_30.setStretch(1, 1)
        self.horizontalLayout_30.setStretch(2, 7)
        self.verticalLayout.addLayout(self.horizontalLayout_30)
        self.frame_20 = QtWidgets.QFrame(self.widget_4)
        self.frame_20.setStyleSheet("QFrame{\n"
"    background-color: qlineargradient(spread:pad, x1:0.438, y1:0.568591, x2:1, y2:1, stop:0 rgba(241, 238, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border:0px solid red;\n"
"    color: rgb(255, 254, 255);\n"
"border-radius:15px\n"
"}")
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_20)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_3 = QtWidgets.QLabel(self.frame_20)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_13.addWidget(self.label_3)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.frame_20)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.horizontalLayout_13.addWidget(self.lineEdit_7)
        self.verticalLayout.addWidget(self.frame_20)
        self.frame_21 = QtWidgets.QFrame(self.widget_4)
        self.frame_21.setStyleSheet("QFrame{\n"
"    background-color: qlineargradient(spread:pad, x1:0.438, y1:0.568591, x2:1, y2:1, stop:0 rgba(241, 238, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border:0px solid red;\n"
"    color: rgb(255, 254, 255);\n"
"border-radius:15px\n"
"}")
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.frame_21)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_5 = QtWidgets.QLabel(self.frame_21)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_19.addWidget(self.label_5)
        self.textEdit = QtWidgets.QTextEdit(self.frame_21)
        self.textEdit.setStyleSheet("QFrame{\n"
"    background-color: rgb(255, 255, 255);\n"
"border:0px solid red;\n"
"    color: rgb(255, 254, 255);\n"
"border-radius:10px\n"
"}")
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout_19.addWidget(self.textEdit)
        self.verticalLayout.addWidget(self.frame_21)
        self.horizontalLayout_44 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_44.addItem(spacerItem7)
        self.pushButton_7 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_44.addWidget(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_44.addWidget(self.pushButton_8)
        self.verticalLayout.addLayout(self.horizontalLayout_44)
        self.horizontalLayout_26.addWidget(self.widget_4)
        self.horizontalLayout_7.addWidget(self.widget_3)
        self.horizontalLayout_6.addWidget(self.frame_5)
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.page_2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_6 = QtWidgets.QFrame(self.page_2)
        self.frame_6.setStyleSheet("QFrame{\n"
"    background-color: rgb(255, 255, 255);\n"
"border:0px solid red;\n"
"    color: rgb(255, 254, 255);\n"
"border-radius:30px\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.scrollArea_4 = QtWidgets.QScrollArea(self.frame_6)
        self.scrollArea_4.setStyleSheet("*{\n"
"    background-color: rgb(255, 255, 255);\n"
"border:0px solid red;\n"
"    color: rgb(255, 254, 255);\n"
"border-radius:30px\n"
"}")
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 711, 599))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)
        self.horizontalLayout_2.addWidget(self.scrollArea_4)
        self.horizontalLayout_5.addWidget(self.frame_6)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.page_3)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.frame_23 = QtWidgets.QFrame(self.page_3)
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_23)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_5 = QtWidgets.QWidget(self.frame_23)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_29 = QtWidgets.QFrame(self.widget_5)
        self.frame_29.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout(self.frame_29)
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_38.addItem(spacerItem8)
        self.label_4 = QtWidgets.QLabel(self.frame_29)
        self.label_4.setStyleSheet("QFrame{\n"
"    background-color: qlineargradient(spread:pad, x1:0.577, y1:0.522727, x2:1, y2:1, stop:0 rgba(201, 187, 241, 253), stop:1 rgba(255, 255, 255, 255));\n"
"border:0px solid red;\n"
"    color: rgb(255, 254, 255);\n"
"border-radius:10px\n"
"}\n"
"")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_38.addWidget(self.label_4)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_38.addItem(spacerItem9)
        self.horizontalLayout_38.setStretch(0, 1)
        self.horizontalLayout_38.setStretch(1, 2)
        self.horizontalLayout_38.setStretch(2, 1)
        self.verticalLayout_3.addWidget(self.frame_29)
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.frame_name = QtWidgets.QFrame(self.widget_5)
        self.frame_name.setStyleSheet("QFrame{\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0.438, y1:0.568591, x2:1, y2:1, stop:0 rgba(241, 238, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    \n"
"border:0px solid red;\n"
"    color: rgb(255, 254, 255);\n"
"border-radius:15px\n"
"}")
        self.frame_name.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_name.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_name.setObjectName("frame_name")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.frame_name)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_name = QtWidgets.QLabel(self.frame_name)
        self.label_name.setStyleSheet("")
        self.label_name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_name.setObjectName("label_name")
        self.horizontalLayout_24.addWidget(self.label_name)
        self.lineEdit_name = QtWidgets.QLineEdit(self.frame_name)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.horizontalLayout_24.addWidget(self.lineEdit_name)
        self.horizontalLayout_34.addWidget(self.frame_name)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_34.addItem(spacerItem10)
        self.frame_sex = QtWidgets.QFrame(self.widget_5)
        self.frame_sex.setStyleSheet("QFrame{\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0.438, y1:0.568591, x2:1, y2:1, stop:0 rgba(241, 238, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border:0px solid red;\n"
"    color: rgb(255, 254, 255);\n"
"border-radius:15px\n"
"}")
        self.frame_sex.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_sex.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_sex.setObjectName("frame_sex")
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout(self.frame_sex)
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.label_sex = QtWidgets.QLabel(self.frame_sex)
        self.label_sex.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_sex.setObjectName("label_sex")
        self.horizontalLayout_35.addWidget(self.label_sex)
        self.comboBox_sex = QtWidgets.QComboBox(self.frame_sex)
        self.comboBox_sex.setObjectName("comboBox_sex")
        self.comboBox_sex.addItem("")
        self.comboBox_sex.addItem("")
        self.horizontalLayout_35.addWidget(self.comboBox_sex)
        self.horizontalLayout_34.addWidget(self.frame_sex)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_34.addItem(spacerItem11)
        self.frame_age = QtWidgets.QFrame(self.widget_5)
        self.frame_age.setStyleSheet("QFrame{\n"
"    background-color: qlineargradient(spread:pad, x1:0.438, y1:0.568591, x2:1, y2:1, stop:0 rgba(241, 238, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border:0px solid red;\n"
"    color: rgb(255, 254, 255);\n"
"border-radius:15px\n"
"}")
        self.frame_age.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_age.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_age.setObjectName("frame_age")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.frame_age)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_age = QtWidgets.QLabel(self.frame_age)
        self.label_age.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_age.setObjectName("label_age")
        self.horizontalLayout_25.addWidget(self.label_age)
        self.lineEdit_age = QtWidgets.QLineEdit(self.frame_age)
        self.lineEdit_age.setObjectName("lineEdit_age")
        self.horizontalLayout_25.addWidget(self.lineEdit_age)
        self.horizontalLayout_34.addWidget(self.frame_age)
        self.frame_type = QtWidgets.QFrame(self.widget_5)
        self.frame_type.setStyleSheet("QFrame{\n"
"    background-color: qlineargradient(spread:pad, x1:0.438, y1:0.568591, x2:1, y2:1, stop:0 rgba(241, 238, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border:0px solid red;\n"
"    color: rgb(255, 254, 255);\n"
"border-radius:15px\n"
"}")
        self.frame_type.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_type.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_type.setObjectName("frame_type")
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout(self.frame_type)
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.label_type = QtWidgets.QLabel(self.frame_type)
        self.label_type.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_type.setObjectName("label_type")
        self.horizontalLayout_42.addWidget(self.label_type)
        self.lineEdit_type = QtWidgets.QLineEdit(self.frame_type)
        self.lineEdit_type.setObjectName("lineEdit_type")
        self.horizontalLayout_42.addWidget(self.lineEdit_type)
        self.horizontalLayout_34.addWidget(self.frame_type)
        self.frame_breed = QtWidgets.QFrame(self.widget_5)
        self.frame_breed.setStyleSheet("QFrame{\n"
"        background-color: qlineargradient(spread:pad, x1:0.438, y1:0.568591, x2:1, y2:1, stop:0 rgba(241, 238, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border:0px solid red;\n"
"    color: rgb(255, 254, 255);\n"
"border-radius:15px\n"
"}")
        self.frame_breed.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_breed.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_breed.setObjectName("frame_breed")
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout(self.frame_breed)
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.label_breed = QtWidgets.QLabel(self.frame_breed)
        self.label_breed.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_breed.setObjectName("label_breed")
        self.horizontalLayout_36.addWidget(self.label_breed)
        self.lineEdit_breed = QtWidgets.QLineEdit(self.frame_breed)
        self.lineEdit_breed.setObjectName("lineEdit_breed")
        self.horizontalLayout_36.addWidget(self.lineEdit_breed)
        self.horizontalLayout_34.addWidget(self.frame_breed)
        self.horizontalLayout_34.setStretch(0, 3)
        self.horizontalLayout_34.setStretch(4, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_34)
        self.frame_28 = QtWidgets.QFrame(self.widget_5)
        self.frame_28.setStyleSheet("QFrame{\n"
"        background-color: qlineargradient(spread:pad, x1:0.438, y1:0.568591, x2:1, y2:1, stop:0 rgba(241, 238, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border:0px solid red;\n"
"    color: rgb(255, 254, 255);\n"
"border-radius:15px\n"
"}")
        self.frame_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout(self.frame_28)
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.label_16 = QtWidgets.QLabel(self.frame_28)
        self.label_16.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_37.addWidget(self.label_16)
        self.textEdit_2 = QtWidgets.QTextEdit(self.frame_28)
        self.textEdit_2.setStyleSheet("QFrame{\n"
"    background-color: rgb(255, 255, 255);\n"
"border:0px solid red;\n"
"    color: rgb(255, 254, 255);\n"
"border-radius:10px\n"
"}")
        self.textEdit_2.setObjectName("textEdit_2")
        self.horizontalLayout_37.addWidget(self.textEdit_2)
        self.verticalLayout_3.addWidget(self.frame_28)
        self.frame_30 = QtWidgets.QFrame(self.widget_5)
        self.frame_30.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_30.setObjectName("frame_30")
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout(self.frame_30)
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_39.addItem(spacerItem12)
        self.pushButton = QtWidgets.QPushButton(self.frame_30)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_39.addWidget(self.pushButton)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_39.addItem(spacerItem13)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_30)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_39.addWidget(self.pushButton_2)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_39.addItem(spacerItem14)
        self.verticalLayout_3.addWidget(self.frame_30)
        self.verticalLayout_2.addWidget(self.widget_5)
        self.scrollArea = QtWidgets.QScrollArea(self.frame_23)
        self.scrollArea.setStyleSheet("*{\n"
"        background-color: rgb(255, 255, 255);\n"
"    border:5px solid;\n"
"    border-color:  qlineargradient(spread:pad, x1:0.438, y1:0.568591, x2:1, y2:1, stop:0 rgba(241, 238, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    color: rgb(255, 254, 255);\n"
"border-radius:10px\n"
"}")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 701, 286))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 1)
        self.horizontalLayout_23.addWidget(self.frame_23)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout(self.page_4)
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.frame_31 = QtWidgets.QFrame(self.page_4)
        self.frame_31.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_31.setObjectName("frame_31")
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout(self.frame_31)
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.frame_31)
        self.scrollArea_3.setStyleSheet("*{\n"
"    background-color: rgb(255, 255, 255);\n"
"border:0px solid red;\n"
"    color: rgb(255, 254, 255);\n"
"border-radius:30px\n"
"}")
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 711, 599))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.horizontalLayout_43.addWidget(self.scrollArea_3)
        self.horizontalLayout_40.addWidget(self.frame_31)
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout(self.page_5)
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.frame_32 = QtWidgets.QFrame(self.page_5)
        self.frame_32.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_32.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_32.setObjectName("frame_32")
        self.horizontalLayout_45 = QtWidgets.QHBoxLayout(self.frame_32)
        self.horizontalLayout_45.setObjectName("horizontalLayout_45")
        self.scrollArea_5 = QtWidgets.QScrollArea(self.frame_32)
        self.scrollArea_5.setStyleSheet("*{\n"
"    background-color: rgb(255, 255, 255);\n"
"border:0px solid red;\n"
"    color: rgb(255, 254, 255);\n"
"border-radius:30px\n"
"}")
        self.scrollArea_5.setWidgetResizable(True)
        self.scrollArea_5.setObjectName("scrollArea_5")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 711, 599))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.scrollArea_5.setWidget(self.scrollAreaWidgetContents_5)
        self.horizontalLayout_45.addWidget(self.scrollArea_5)
        self.horizontalLayout_41.addWidget(self.frame_32)
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.horizontalLayout_47 = QtWidgets.QHBoxLayout(self.page_6)
        self.horizontalLayout_47.setObjectName("horizontalLayout_47")
        self.frame_33 = QtWidgets.QFrame(self.page_6)
        self.frame_33.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_33.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_33.setObjectName("frame_33")
        self.horizontalLayout_46 = QtWidgets.QHBoxLayout(self.frame_33)
        self.horizontalLayout_46.setObjectName("horizontalLayout_46")
        self.widget_7 = QtWidgets.QWidget(self.frame_33)
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_7)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_34 = QtWidgets.QFrame(self.widget_7)
        self.frame_34.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_34.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_34.setObjectName("frame_34")
        self.horizontalLayout_48 = QtWidgets.QHBoxLayout(self.frame_34)
        self.horizontalLayout_48.setObjectName("horizontalLayout_48")
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_48.addItem(spacerItem15)
        self.label_7 = QtWidgets.QLabel(self.frame_34)
        self.label_7.setStyleSheet("QFrame{\n"
"    background-color: qlineargradient(spread:pad, x1:0.577, y1:0.522727, x2:1, y2:1, stop:0 rgba(201, 187, 241, 253), stop:1 rgba(255, 255, 255, 255));\n"
"    \n"
"border:0px solid red;\n"
"    color: rgb(255, 254, 255);\n"
"border-radius:10px\n"
"}\n"
"")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_48.addWidget(self.label_7)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_48.addItem(spacerItem16)
        self.horizontalLayout_48.setStretch(0, 1)
        self.horizontalLayout_48.setStretch(1, 2)
        self.horizontalLayout_48.setStretch(2, 1)
        self.verticalLayout_4.addWidget(self.frame_34)
        self.horizontalLayout_58 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_58.setObjectName("horizontalLayout_58")
        self.frame_breed_3 = QtWidgets.QFrame(self.widget_7)
        self.frame_breed_3.setStyleSheet("QFrame{\n"
"    background-color: qlineargradient(spread:pad, x1:0.438, y1:0.568591, x2:1, y2:1, stop:0 rgba(241, 238, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border:0px solid red;\n"
"    color: rgb(255, 254, 255);\n"
"border-radius:15px\n"
"}")
        self.frame_breed_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_breed_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_breed_3.setObjectName("frame_breed_3")
        self.horizontalLayout_57 = QtWidgets.QHBoxLayout(self.frame_breed_3)
        self.horizontalLayout_57.setObjectName("horizontalLayout_57")
        self.label_breed_3 = QtWidgets.QLabel(self.frame_breed_3)
        self.label_breed_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_breed_3.setObjectName("label_breed_3")
        self.horizontalLayout_57.addWidget(self.label_breed_3)
        self.lineEdit_breed_3 = QtWidgets.QLineEdit(self.frame_breed_3)
        self.lineEdit_breed_3.setObjectName("lineEdit_breed_3")
        self.horizontalLayout_57.addWidget(self.lineEdit_breed_3)
        self.horizontalLayout_58.addWidget(self.frame_breed_3)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_58.addItem(spacerItem17)
        self.frame_name_2 = QtWidgets.QFrame(self.widget_7)
        self.frame_name_2.setStyleSheet("QFrame{\n"
"    background-color: qlineargradient(spread:pad, x1:0.438, y1:0.568591, x2:1, y2:1, stop:0 rgba(241, 238, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border:0px solid red;\n"
"    color: rgb(255, 254, 255);\n"
"border-radius:15px\n"
"}")
        self.frame_name_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_name_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_name_2.setObjectName("frame_name_2")
        self.horizontalLayout_50 = QtWidgets.QHBoxLayout(self.frame_name_2)
        self.horizontalLayout_50.setObjectName("horizontalLayout_50")
        self.label_name_2 = QtWidgets.QLabel(self.frame_name_2)
        self.label_name_2.setStyleSheet("")
        self.label_name_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_name_2.setObjectName("label_name_2")
        self.horizontalLayout_50.addWidget(self.label_name_2)
        self.lineEdit_name_2 = QtWidgets.QLineEdit(self.frame_name_2)
        self.lineEdit_name_2.setObjectName("lineEdit_name_2")
        self.horizontalLayout_50.addWidget(self.lineEdit_name_2)
        self.horizontalLayout_58.addWidget(self.frame_name_2)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_58.addItem(spacerItem18)
        self.frame_breed_2 = QtWidgets.QFrame(self.widget_7)
        self.frame_breed_2.setStyleSheet("QFrame{\n"
"    background-color: qlineargradient(spread:pad, x1:0.438, y1:0.568591, x2:1, y2:1, stop:0 rgba(241, 238, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border:0px solid red;\n"
"    color: rgb(255, 254, 255);\n"
"border-radius:15px\n"
"}")
        self.frame_breed_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_breed_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_breed_2.setObjectName("frame_breed_2")
        self.horizontalLayout_54 = QtWidgets.QHBoxLayout(self.frame_breed_2)
        self.horizontalLayout_54.setObjectName("horizontalLayout_54")
        self.label_breed_2 = QtWidgets.QLabel(self.frame_breed_2)
        self.label_breed_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_breed_2.setObjectName("label_breed_2")
        self.horizontalLayout_54.addWidget(self.label_breed_2)
        self.lineEdit_breed_2 = QtWidgets.QLineEdit(self.frame_breed_2)
        self.lineEdit_breed_2.setObjectName("lineEdit_breed_2")
        self.horizontalLayout_54.addWidget(self.lineEdit_breed_2)
        self.horizontalLayout_58.addWidget(self.frame_breed_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_58)
        self.horizontalLayout_49 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_49.setObjectName("horizontalLayout_49")
        self.frame_sex_2 = QtWidgets.QFrame(self.widget_7)
        self.frame_sex_2.setStyleSheet("QFrame{\n"
"    background-color: qlineargradient(spread:pad, x1:0.438, y1:0.568591, x2:1, y2:1, stop:0 rgba(241, 238, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border:0px solid red;\n"
"    color: rgb(255, 254, 255);\n"
"border-radius:15px\n"
"}")
        self.frame_sex_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_sex_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_sex_2.setObjectName("frame_sex_2")
        self.horizontalLayout_51 = QtWidgets.QHBoxLayout(self.frame_sex_2)
        self.horizontalLayout_51.setObjectName("horizontalLayout_51")
        self.label_sex_2 = QtWidgets.QLabel(self.frame_sex_2)
        self.label_sex_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_sex_2.setObjectName("label_sex_2")
        self.horizontalLayout_51.addWidget(self.label_sex_2)
        self.comboBox_sex_2 = QtWidgets.QComboBox(self.frame_sex_2)
        self.comboBox_sex_2.setObjectName("comboBox_sex_2")
        self.comboBox_sex_2.addItem("")
        self.comboBox_sex_2.addItem("")
        self.horizontalLayout_51.addWidget(self.comboBox_sex_2)
        self.horizontalLayout_49.addWidget(self.frame_sex_2)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_49.addItem(spacerItem19)
        self.frame_age_2 = QtWidgets.QFrame(self.widget_7)
        self.frame_age_2.setStyleSheet("QFrame{\n"
"    background-color: qlineargradient(spread:pad, x1:0.438, y1:0.568591, x2:1, y2:1, stop:0 rgba(241, 238, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border:0px solid red;\n"
"    color: rgb(255, 254, 255);\n"
"border-radius:15px\n"
"}")
        self.frame_age_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_age_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_age_2.setObjectName("frame_age_2")
        self.horizontalLayout_52 = QtWidgets.QHBoxLayout(self.frame_age_2)
        self.horizontalLayout_52.setObjectName("horizontalLayout_52")
        self.label_age_2 = QtWidgets.QLabel(self.frame_age_2)
        self.label_age_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_age_2.setObjectName("label_age_2")
        self.horizontalLayout_52.addWidget(self.label_age_2)
        self.lineEdit_age_2 = QtWidgets.QLineEdit(self.frame_age_2)
        self.lineEdit_age_2.setObjectName("lineEdit_age_2")
        self.horizontalLayout_52.addWidget(self.lineEdit_age_2)
        self.horizontalLayout_49.addWidget(self.frame_age_2)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_49.addItem(spacerItem20)
        self.frame_type_2 = QtWidgets.QFrame(self.widget_7)
        self.frame_type_2.setStyleSheet("QFrame{\n"
"    background-color: qlineargradient(spread:pad, x1:0.438, y1:0.568591, x2:1, y2:1, stop:0 rgba(241, 238, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border:0px solid red;\n"
"    color: rgb(255, 254, 255);\n"
"border-radius:15px\n"
"}")
        self.frame_type_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_type_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_type_2.setObjectName("frame_type_2")
        self.horizontalLayout_53 = QtWidgets.QHBoxLayout(self.frame_type_2)
        self.horizontalLayout_53.setObjectName("horizontalLayout_53")
        self.label_type_2 = QtWidgets.QLabel(self.frame_type_2)
        self.label_type_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_type_2.setObjectName("label_type_2")
        self.horizontalLayout_53.addWidget(self.label_type_2)
        self.lineEdit_type_2 = QtWidgets.QLineEdit(self.frame_type_2)
        self.lineEdit_type_2.setObjectName("lineEdit_type_2")
        self.horizontalLayout_53.addWidget(self.lineEdit_type_2)
        self.horizontalLayout_49.addWidget(self.frame_type_2)
        self.horizontalLayout_49.setStretch(2, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_49)
        self.frame_35 = QtWidgets.QFrame(self.widget_7)
        self.frame_35.setStyleSheet("QFrame{\n"
"    background-color: qlineargradient(spread:pad, x1:0.438, y1:0.568591, x2:1, y2:1, stop:0 rgba(241, 238, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border:0px solid red;\n"
"    color: rgb(255, 254, 255);\n"
"border-radius:15px\n"
"}")
        self.frame_35.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_35.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_35.setObjectName("frame_35")
        self.horizontalLayout_55 = QtWidgets.QHBoxLayout(self.frame_35)
        self.horizontalLayout_55.setObjectName("horizontalLayout_55")
        self.label_17 = QtWidgets.QLabel(self.frame_35)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_55.addWidget(self.label_17)
        self.textEdit_3 = QtWidgets.QTextEdit(self.frame_35)
        self.textEdit_3.setStyleSheet("QFrame{\n"
"    background-color: rgb(255, 255, 255);\n"
"border:0px solid red;\n"
"    color: rgb(255, 254, 255);\n"
"border-radius:10px\n"
"}")
        self.textEdit_3.setObjectName("textEdit_3")
        self.horizontalLayout_55.addWidget(self.textEdit_3)
        self.verticalLayout_4.addWidget(self.frame_35)
        self.frame_36 = QtWidgets.QFrame(self.widget_7)
        self.frame_36.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_36.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_36.setObjectName("frame_36")
        self.horizontalLayout_56 = QtWidgets.QHBoxLayout(self.frame_36)
        self.horizontalLayout_56.setObjectName("horizontalLayout_56")
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_56.addItem(spacerItem21)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_36)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_56.addWidget(self.pushButton_3)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_56.addItem(spacerItem22)
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_36)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_56.addWidget(self.pushButton_6)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_56.addItem(spacerItem23)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_36)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_56.addWidget(self.pushButton_5)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_56.addItem(spacerItem24)
        self.verticalLayout_4.addWidget(self.frame_36)
        self.verticalLayout_4.setStretch(0, 1)
        self.verticalLayout_4.setStretch(1, 1)
        self.verticalLayout_4.setStretch(2, 1)
        self.verticalLayout_4.setStretch(3, 4)
        self.verticalLayout_4.setStretch(4, 1)
        self.horizontalLayout_46.addWidget(self.widget_7)
        self.horizontalLayout_47.addWidget(self.frame_33)
        self.stackedWidget.addWidget(self.page_6)
        self.verticalLayout_13.addWidget(self.stackedWidget)
        self.horizontalLayout_18.addWidget(self.frame_2)
        self.horizontalLayout_18.setStretch(0, 1)
        self.horizontalLayout_18.setStretch(1, 7)
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget_5.setCurrentIndex(1)
        self.listWidget_2.setCurrentRow(-1)
        self.listWidget_3.setCurrentRow(-1)
        self.stackedWidget.setCurrentIndex(6)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.textEdit.setTextColor(QColor(0, 0, 0))
        self.textEdit_2.setTextColor(QColor(0, 0, 0))
        self.textEdit_3.setTextColor(QColor(0, 0, 0))
        self.flowLayout = FlowLayout()
        # self.flowLayout = QGridLayout()
        # iwidget = Ui_CoverItemWidget.Ui_CoverItemWidget()
        # iwidget = pet_item.Pet_Item(self.widget)
        # iwidget.init("图片", "飞飞", "亲人", "1岁", "金毛", "1")
        # iwidget.show()
        # self.flowLayout.addWidget(iwidget)
        # flowLayout.addWidget(QPushButton("Short"))
        # # pet_pic, pet_name, pet_nature, pet_age, pet_breed
        # flowLayout.addWidget(QPushButton("Different text"))
        # flowLayout.addWidget(pet_item.Pet_Item())
        # flowLayout.addWidget(QPushButton("Even longer button text"))
        # flowLayout.addWidget(QLabel("test"))
        self.scrollAreaWidgetContents_2.setLayout(self.flowLayout)
        self.scrollArea_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)

        # self.scrollArea_2.setWidgetResizable(False)

        self.flowLayout_adopt = FlowLayout()
        self.scrollAreaWidgetContents_4.setLayout(self.flowLayout_adopt)
        self.scrollArea_4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)

        self.flowLayout_pet_adm = FlowLayout()
        self.scrollAreaWidgetContents.setLayout(self.flowLayout_pet_adm)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)

        self.flowLayout_app_adm = FlowLayout()
        self.scrollAreaWidgetContents_3.setLayout(self.flowLayout_app_adm)
        self.scrollArea_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)

        self.flowLayout_app_adm_over = FlowLayout()
        self.scrollAreaWidgetContents_5.setLayout(self.flowLayout_app_adm_over)
        self.scrollArea_5.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)

        self.listWidget_2.itemClicked.connect(self.changePage)
        self.listWidget_3.itemClicked.connect(self.changePage)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_23.setText(_translate("MainWindow", "SilverFox_Ankha"))
        __sortingEnabled = self.listWidget_2.isSortingEnabled()
        self.listWidget_2.setSortingEnabled(False)
        item = self.listWidget_2.item(0)
        item.setText(_translate("MainWindow", "待领养"))
        item = self.listWidget_2.item(1)
        item.setText(_translate("MainWindow", "申请表"))
        item = self.listWidget_2.item(2)
        item.setText(_translate("MainWindow", "我的申请"))
        self.listWidget_2.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.listWidget_3.isSortingEnabled()
        self.listWidget_3.setSortingEnabled(False)
        item = self.listWidget_3.item(0)
        item.setText(_translate("MainWindow", "待领养管理"))
        item = self.listWidget_3.item(1)
        item.setText(_translate("MainWindow", "待处理申请"))
        item = self.listWidget_3.item(2)
        item.setText(_translate("MainWindow", "我已处理"))
        self.listWidget_3.setSortingEnabled(__sortingEnabled)
        self.pushButton_4.setText(_translate("MainWindow", "Exit"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#222222;\">领养申请</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#222222;\">姓名</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#222222;\">性别</span></p></body></html>"))
        self.comboBox.setItemText(0, _translate("MainWindow", "男"))
        self.comboBox.setItemText(1, _translate("MainWindow", "女"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#222222;\">年龄</span></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#222222;\">家庭住址</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#222222;\">家庭总人数</span></p></body></html>"))
        self.checkBox.setText(_translate("MainWindow", "已经经过全体家庭成员同意领养"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#222222;\">联系电话</span></p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#222222;\">邮箱</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#222222;\">申请宠物编号</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#222222;\">申请理由</span></p></body></html>"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pushButton_7.setText(_translate("MainWindow", "申请"))
        self.pushButton_8.setText(_translate("MainWindow", "清空"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#222222;\">新增待领养小动物</span></p></body></html>"))
        self.label_name.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#222222;\">名字</span></p></body></html>"))
        self.label_sex.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#222222;\">公母</span></p></body></html>"))
        self.comboBox_sex.setItemText(0, _translate("MainWindow", "公"))
        self.comboBox_sex.setItemText(1, _translate("MainWindow", "母"))
        self.label_age.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#222222;\">年龄</span></p></body></html>"))
        self.label_type.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#222222;\">种类</span></p></body></html>"))
        self.label_breed.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#222222;\">品种</span></p></body></html>"))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#222222;\">性格</span></p></body></html>"))
        self.textEdit_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "新增"))
        self.pushButton_2.setText(_translate("MainWindow", "取消"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#222222;\">修改待领养小动物信息</span></p></body></html>"))
        self.label_breed_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#222222;\">编号</span></p></body></html>"))
        self.label_name_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#222222;\">名字</span></p></body></html>"))
        self.label_breed_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#222222;\">品种</span></p></body></html>"))
        self.label_sex_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#222222;\">公母</span></p></body></html>"))
        self.comboBox_sex_2.setItemText(0, _translate("MainWindow", "公"))
        self.comboBox_sex_2.setItemText(1, _translate("MainWindow", "母"))
        self.label_age_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#222222;\">年龄</span></p></body></html>"))
        self.label_type_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#222222;\">种类</span></p></body></html>"))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#222222;\">性格</span></p></body></html>"))
        self.textEdit_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pushButton_3.setText(_translate("MainWindow", "修改"))
        self.pushButton_6.setText(_translate("MainWindow", "删除"))
        self.pushButton_5.setText(_translate("MainWindow", "取消"))

    def changePage(self, item):

        if self.stackedWidget_5.currentIndex() == 0:
            print("0000")
            index = self.listWidget_2.indexFromItem(item).row()
            print(index)
            if index == 2:
                self.stackedWidget.setCurrentIndex(2)
            elif index == 0:
                self.stackedWidget.setCurrentIndex(0)
            elif index == 1:
                self.stackedWidget.setCurrentIndex(1)
        else:
            print("1111")
            index = self.listWidget_3.indexFromItem(item).row()
            print(index)
            if index == 0:
                self.stackedWidget.setCurrentIndex(3)
            elif index == 1:
                self.stackedWidget.setCurrentIndex(4)
            elif index == 2:
                self.stackedWidget.setCurrentIndex(5)




